<a href="https://colab.research.google.com/github/DakshL9/Compute_01-02/blob/main/Compute_ML_Task01_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Fetch

In [92]:
from google.colab import drive

drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/bank-additional-full.csv",
    sep=";"
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Data Explore

In [94]:
df.shape

(41188, 21)

In [95]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [96]:
df.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [98]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

# Null & Duplicates

In [99]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [100]:
df.duplicated().sum()  # No Duplicates

np.int64(12)

In [101]:
print((df['pdays'] == -1).sum()) #missing values the site says that exist but are =-1

df["previously_contacted"] = (df["pdays"] != 999) # creation of binary category for easier understanding

0

In [102]:
df['poutcome']=df['poutcome'].fillna(value='nonexistent') #previously not contacted at all
df['contact']=df['contact'].fillna(value='unknown') # Not entered? Investigate later.
df['job']=df['job'].fillna(value='unknown') # As mentioned in variables table
df['education']=df['education'].fillna(value='unknown') # As mentioned in variables table

In [103]:
print(df['day_of_week'].unique()) #confirming if its day of month or week

df['day_of_week'] = df['day_of_week'].astype(str) #categorical, day 2 !< day 31

['mon' 'tue' 'wed' 'thu' 'fri']

In [109]:
# Segregation of cols into num/cat

numerical_cols = ['age', 'previous', 'emp.var.rate', 'cons.price.idx',
                    'cons.conf.idx', 'euribor3m', 'nr.employed']
categorical_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'day_of_week', 'month','previously_contacted', 'poutcome', ]
cols = numerical_cols + categorical_cols
target_var = 'y'

# 'duration' dropped as known post-call
# 'campaign' does not necessarily affect the client's choice to subscribe
# 'pdays' unnecessary as it is replaced by 'previously_contacted'

#Train Test Split

In [134]:
from sklearn.model_selection import train_test_split

X = df[cols]
y = df[target_var]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape

((32950, 18), (8238, 18))

#Standardization & Encoding

In [ ]:
from sklearn.pipeline import make_pipeline

numeric_transformer = make_pipeline(SimpleImputer(strategy="median"), StandardScaler()) #SimpleImputer replaces missing values with the median and StandardScaler scales the data to have a mean of 0 and a standard deviation of 1

categorical_transformer = make_pipeline(SimpleImputer(strategy="most_frequent"), OneHotEncoder(handle_unknown="ignore", sparse_output=True)) #SimpleImputer replaces missing values with the most frequent value. OneHotEncoder converts categories into numerical columns. Handle Unknown simply means that if the model encounters a category that it hasn't seen during training, it will ignore it. Sparse output True means that it will return a sparse matrix which is a more efficient way to store data.

preprocessor = ColumnTransformer([("num", numeric_transformer, numerical_features), ("cat", categorical_transformer, categorical_features)])

lda_qda_preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_features),
    ("cat", make_pipeline(SimpleImputer(strategy="most_frequent"), OneHotEncoder(handle_unknown="ignore", sparse_output=False)), categorical_features)
])d

In [122]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

tr = [ ("cat", OneHotEncoder(), categorical_cols), ('num', StandardScaler(), numerical_cols)]

col_transform = ColumnTransformer(transformers=tr)
featurizer = col_transform.fit(df[cols]);

model_df = featurizer.transform(df[cols])

model_df = pd.DataFrame.sparse.from_spmatrix(model_df)
model_df

,0,1,2,3,4,5,6,7,8,9,...,52,53,54,55,56,57,58,59,60,61
0,0,0,0,1.0,0,0,0,0,0,0,...,0,1.0,0,1.533034,-0.349494,0.648092,0.722722,0.886447,0.71246,0.33168
1,0,0,0,0,0,0,0,1.0,0,0,...,0,1.0,0,1.628993,-0.349494,0.648092,0.722722,0.886447,0.71246,0.33168
2,0,0,0,0,0,0,0,1.0,0,0,...,0,1.0,0,-0.290186,-0.349494,0.648092,0.722722,0.886447,0.71246,0.33168
3,1.0,0,0,0,0,0,0,0,0,0,...,0,1.0,0,-0.002309,-0.349494,0.648092,0.722722,0.886447,0.71246,0.33168
4,0,0,0,0,0,0,0,1.0,0,0,...,0,1.0,0,1.533034,-0.349494,0.648092,0.722722,0.886447,0.71246,0.33168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,0,0,0,0,0,1.0,0,0,0,0,...,0,1.0,0,3.164336,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697
41184,0,1.0,0,0,0,0,0,0,0,0,...,0,1.0,0,0.573445,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697
41185,0,0,0,0,0,1.0,0,0,0,0,...,0,1.0,0,1.533034,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697
41186,0,0,0,0,0,0,0,0,0,1.0,...,0,1.0,0,0.381527,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697
41187,0,0,0,0,0,1.0,0,0,0,0,...,1.0,0,0,3.260295,1.671136,-0.752343,2.058168,-2.224953,-1.495186,-2.815697